### PR TITLE
Added EIP712 to `validateUserOp` for `MultipleOwnerECDSAValidator`

### PR DESCRIPTION
**Pull request by lbw33**
## Description

- Added EIP signatures to `validateUserOp`for `MultipleOwnerECDSAValidator`
- Fixed test suite so all tests pass

## Motivation and Context

- EIP712 signature support for UserOps

## How Has This Been Tested?

- test suite

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by 0xSulpiride** [comment]
This is going to break the current flow of things?
I think to support EIP-712 we need to implement this in our contracts: https://eips.ethereum.org/EIPS/eip-1271

This way people can use EIP-6492 this validate their signatures: https://eips.ethereum.org/EIPS/eip-6492

So, I'd suggest exposing this function in our wallets:
```
function isValidSignature(
    bytes32 _hash, 
    bytes memory _signature)
    public
    view 
    returns (bytes4 magicValue);
```

**Comment by 0xSulpiride** [comment]
oh, we already have this in our v1 wallets: https://github.com/etherspot/etherspot-prime-contracts/blob/master/src/etherspot-wallet-v1/wallet/EtherspotWallet.sol#L80-L101

so we just need to copy that to v2

**Comment by lbw33** [comment]
We have that in the MultipleOwnerECDSAValidator as that is what will need to handle the signatures

**Review by ch4r10t33r — APPROVED** [review]
Can you pls update the benchmarks file for the gas consumption as a result of these changes.

**Review by 0xSulpiride — APPROVED** [review]

**Pull request merged**
