### PR TITLE
ERC6900 Reference Implementation and Foundry Setup

### PR DESCRIPTION
**Pull request by lbw33**
## Description

- Foundry set up in repo.
- Set Foundry configs and remappings.
- Set up ERC6900 reference implementation as submodule in base repo.
- Moved over required contracts from reference implementation to base repo.
- Moved over required tests for moved contracts in base repo.
- Moved modular account errors to separate library.
- Renamed modular account to V2 of our wallet.
- Fixed broken tests.
- Updated submodules and fixed import issues in EtherspotPaymaster.

## Motivation and Context

- To start implementation of ERC6900 for Etherspot account abstraction wallet.

## How Has This Been Tested?

- Moving required reference contracts from reference submodule to base repo and running tests from reference against contracts.

## Screenshots (if appropriate):
Screenshot 2023-11-21 at 10 07 14

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by ch4r10t33r — COMMENTED** [review]
Why do we have both Apache and MIT licenses in the same repo? Is this copied over from elsewhere? @lbw33

**Comment by lbw33** [comment]
> Why do we have both Apache and MIT licenses in the same repo? Is this copied over from elsewhere? @lbw33

I have changed some of the licenses that were incorrect. The ones that haven't been changed are contracts from the reference implementation that have no changes applied to them.

**Review by ch4r10t33r — APPROVED** [review]
LGTM

**Comment by ch4r10t33r** [comment]
@0xSulpiride @vignesha22 Pls review this PR.

**Review by 0xSulpiride — APPROVED** [review]
LGTM

**Pull request merged**
